// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Ttvkvb6WpU5e36h-zvYmn8LnVWamt-U',
    appId: '1:1058016940124:web:9ebcbe69a5d1aa732ad699',
    messagingSenderId: '1058016940124',
    projectId: 'flutter-auth-demo-d9838',
    authDomain: 'flutter-auth-demo-d9838.firebaseapp.com',
    storageBucket: 'flutter-auth-demo-d9838.appspot.com',
    measurementId: 'G-WYWLFYXSQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFdhGapDMifhdx1UGoscGYt1GkBhBgdc0',
    appId: '1:1058016940124:android:27e767581195d05d2ad699',
    messagingSenderId: '1058016940124',
    projectId: 'flutter-auth-demo-d9838',
    storageBucket: 'flutter-auth-demo-d9838.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsSJPAFbWMuZdOJZmOLJ5rssek8Sls84s',
    appId: '1:1058016940124:ios:959f3ad2a93234182ad699',
    messagingSenderId: '1058016940124',
    projectId: 'flutter-auth-demo-d9838',
    storageBucket: 'flutter-auth-demo-d9838.appspot.com',
    iosBundleId: 'com.example.loginSignupWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsSJPAFbWMuZdOJZmOLJ5rssek8Sls84s',
    appId: '1:1058016940124:ios:49171430adf7e3982ad699',
    messagingSenderId: '1058016940124',
    projectId: 'flutter-auth-demo-d9838',
    storageBucket: 'flutter-auth-demo-d9838.appspot.com',
    iosBundleId: 'com.example.loginSignupWithFirebase.RunnerTests',
  );
}
